import React from "react";
import Nav from "../nav/Nav";
import Footer from "../Footer";
import PRCompo1 from "../PR_compo_1";

export default function PrivacyPolicy() {
  return (
    <section className="bg_color">
      <header className=" py-8  sm:py-10 lg:py-12 ">
        <Nav />
      </header>
      <main className=" mx-auto pb-8 flex flex-col items-center justify-center gap-8 px-4 pt-5 text-white sm:w-[80%] sm:px-0 md:w-[70%]">
        <div className="PR_Page1">
          <span className="mb-2 inline-block text-2xl font-semibold sm:text-3xl">
            Privacy Policy
          </span>
          <br />
          <span className="text-xl">Last updated: December 25, 2022</span>
          <br />
          <p>
            This Privacy Policy describes Our policies and procedures on the
            collection, use and disclosure of Your information when You use the
            Service and tells You about Your privacy rights and how the law
            protects You. We use Your Personal data to provide and improve the
            Service. By using the Service, You agree to the collection and use
            of information in accordance with this Privacy Policy. This
          </p>
        </div>
        <div className="PR_Page1.2">
          <h1 className=" mb-3  text-xl  font-semibold text-[#5DCBC4] sm:text-center sm:text-2xl md:text-3xl ">
            Interpretation
          </h1>
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </div>
        <div className="PR_Page1.3">
          <h1 className=" mb-3  text-xl  font-semibold text-[#5DCBC4] sm:text-center sm:text-2xl md:text-3xl ">
            Definitions
          </h1>
          <span>For the purposes of this Privacy Policy:</span>
          <br />
          <div className="mt-4 ps-4 sm:ps-8 md:ps-12">
            <PRCompo1 subHeading="Account">
              means a unique account created for You to access our Service or
              parts of our Service.
            </PRCompo1>
            <PRCompo1 subHeading="Company">
              (referred to as either &quot;the Company&quot;, &quot;We&quot;,
              &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to
              example .
            </PRCompo1>
            <PRCompo1 subHeading="Cookies">
              are small files that are placed on Your computer, mobile device or
              any other device by a website, containing the details of Your
              browsing history on that website among its many uses.
            </PRCompo1>
            <PRCompo1 subHeading="Country">
              refers to: California, United States
            </PRCompo1>
            <PRCompo1 subHeading="Device">
              means any device that can access the Service such as a computer, a
              cellphone or a digital tablet.
            </PRCompo1>
            <PRCompo1 subHeading="Personal Data">
              refers to any information that relates to an identified or
              identifiable individual.
            </PRCompo1>
            <PRCompo1 subHeading="Service">refers to the Website.</PRCompo1>
            <PRCompo1 subHeading="Service Provider">
              means any natural or legal person who processes the data on behalf
              of the Company. It refers to third-party companies or individuals
              employed by the Company to facilitate the Service, to provide the
              Service on behalf of the Company, to perform services related to
              the Service or to assist the Company in analyzing how the Service
              is used.
            </PRCompo1>
            <PRCompo1 subHeading="Usage Data">
              refers to data collected automatically either generated by the use
              of the Service or from the Service infrastructure itself (for
              example, the duration of a page visit).
            </PRCompo1>
            <PRCompo1 subHeading="Usage Data">
              refers to data collected automatically, either generated by the
              use of the Service or from the Service infrastructure itself (for
              example, the duration of a page visit).
            </PRCompo1>
            <PRCompo1 subHeading="Website">
              refers to example , accessible from http://example.com/
            </PRCompo1>
          </div>
        </div>
        <div className="PR_Page2">
          <h1 className=" mb-3  text-xl  font-semibold text-[#5DCBC4] sm:text-center sm:text-2xl md:text-3xl ">
            Types of Data Collected
          </h1>
          <PRCompo1
            subHeading="Personal Data"
            subHeadingClass="inline-block w-full"
          >
            While using Our Service, We may ask You to provide Us with certain
            personally identifiable information that can be used to contact or
            identify You. Personally identifiable information may include, but
            is not limited to:
            <br />
            <span className="block ps-5">
              Email address <br /> Usage Data
            </span>
          </PRCompo1>
        </div>
        <div className="PR_Page2.2">
          <PRCompo1
            subHeading="Usage Data"
            subHeadingClass="inline-block w-full"
          >
            <span>
              Usage Data is collected automatically when using the Service.
            </span>
            <br /> <br />
            Usage Data may include information such as Your Device&#39;s
            Internet Protocol address (e.g. IP address), browser type, browser
            version, the pages of our Service that You visit, the time and date
            of Your visit, the time spent on those pages, unique device
            identifiers and other diagnostic data. <br /> <br />
            When You access the Service by or through a mobile device, We may
            collect certain information automatically, including, but not
            limited to, the type of mobile device You use, Your mobile device
            unique ID, the IP address of Your mobile device, Your mobile
            operating system, the type of mobile Internet browser You use,
            unique device identifiers and other diagnostic data. <br /> <br />
            We may also collect information that Your browser sends whenever You
            visit our Service or when You access the Service by or through a
            mobile device.
            <br />
          </PRCompo1>
          <PRCompo1
            subHeading="Tracking Technologies and Cookies"
            subHeadingClass="inline-block w-full"
          >
            We use Cookies and similar tracking technologies to track the
            activity on Our Service and store certain information. Tracking
            technologies used are beacons, tags, and scripts to collect and
            track information and to improve and analyze Our Service. The
            technologies We use may include:
          </PRCompo1>
          <ul className="mt-4 list-disc ps-4 sm:ps-8 md:ps-12">
            <li>
              <PRCompo1 subHeading="Cookies or Browser Cookies.">
                A cookie is a small file placed on Your Device. You can instruct
                Your browser to refuse all Cookies or to indicate when a Cookie
                is being sent. However, if You do not accept Cookies, You may
                not be able to use some parts of our Service. Unless you have
                adjusted Your browser setting so that it will refuse Cookies,
                our Service may use Cookies.
              </PRCompo1>
            </li>
            <li>
              <PRCompo1 subHeading="Web Beacons.">
                Certain sections of our Service and our emails may contain small
                electronic files known as web beacons (also referred to as clear
                gifs, pixel tags, and single-pixel gifs) that permit the
                Company, for example, to count users who have visited those
                pages or opened an email and for other related website
                statistics (for example, recording the popularity of a certain
                section and verifying system and server integrity).
              </PRCompo1>
            </li>
          </ul>
        </div>
        <div className="PR_Page3.2">
          <br />
          <br />
          Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies.
          Persistent Cookies remain on Your personal computer or mobile device
          when You go offline, while Session Cookies are deleted
          <br />
          <br />
          as soon as You close Your web browser. Learn more about cookies on the
          Free Privacy Policy website article.
          <br />
          <br />
          <div className="mt-4 list-disc ps-4 sm:ps-8 md:ps-12">
            <PRCompo1 subHeading="Necessary / Essential Cookies">
              <br />
              <span className="block ps-5">
                Type: Session Cookies <br />
                Administered by: Us
              </span>{" "}
              Purpose: These Cookies are essential to provide You with services
              available through the Website and to enable You to use some of its
              features. They help to authenticate users and prevent fraudulent
              use of user accounts. Without these Cookies, the services that You
              have asked for cannot be provided, and We only use these Cookies
              to provide You with those services.
            </PRCompo1>
            <PRCompo1 subHeading="Cookies Policy / Notice Acceptance Cookies">
              <br />
              <span className="block ps-5">
                Type: Persistent Cookies
                <br />
                Administered by: Us
              </span>
              Purpose: These Cookies identify if users have accepted the use of
              cookies on the Website.
            </PRCompo1>
            <PRCompo1 subHeading="Functionality Cookies">
              <br />
              <span className="block ps-5">
                Type: Persistent Cookies <br />
                Administered by: Us
              </span>
              Purpose: These Cookies allow us to remember choices You make when
              You use the Website, such as remembering your login details or
              language preference. The purpose of these Cookies is to provide
              You with a more personal experience and to avoid You having to
              re-enter your preferences every time You use the Website.
            </PRCompo1>
            For more information about the cookies we use and your choices
            regarding cookies, please visit our Cookies Policy or the Cookies
            section of our Privacy Policy.
          </div>
        </div>
        <div className="PR_Page3.3">
          <PRCompo1
            subHeading="Use of Your Personal Data"
            subHeadingClass="inline-block w-full"
          >
            The Company may use Personal Data for the following purposes:
            <div>
              <PRCompo1
                subHeading="To provide and maintain our Service,"
                childrenClass="mt-4"
              >
                including to monitor the usage of our Service.
              </PRCompo1>
              <PRCompo1
                subHeading="To manage Your Account:"
                childrenClass="mt-4"
              >
                to manage Your registration as a user of the Service. The
                Personal Data You provide can give You access to different
                functionalities of the Service that are available to You as a
                registered user.
              </PRCompo1>
              <PRCompo1
                subHeading="For the performance of a contract:"
                childrenClass="mt-4"
              >
                the development, compliance and undertaking of the purchase
                contract for the products, items or services You have purchased
                or of any other contract with Us through the Service.
              </PRCompo1>
              <PRCompo1 subHeading="To contact You:" childrenClass="mt-4">
                To contact You by email, telephone calls, SMS, or other
                equivalent forms of electronic communication, such as a mobile
                application&#39;s push notifications regarding updates or
                informative communications related to the functionalities,
                products or contracted services, including the security updates,
                when necessary or reasonable for their implementation.
              </PRCompo1>
              <PRCompo1 subHeading="To provide You" childrenClass="mt-4">
                with news, special offers and general information about other
                goods, services and events which we offer that are similar to
                those that you have already purchased or enquired about unless
                You have opted not to receive such information.
              </PRCompo1>
              <PRCompo1
                subHeading="To manage Your requests:"
                childrenClass="mt-4"
              >
                To attend and manage Your requests to Us.
              </PRCompo1>
              <PRCompo1
                subHeading="For business transfers:"
                childrenClass="mt-4"
              >
                We may use Your information to evaluate or conduct a merger,
                divestiture, restructuring, reorganization, dissolution, or
                other sale or transfer of some or all of Our assets, whether as
                a going concern or as part of bankruptcy, liquidation, or
                similar proceeding, in which Personal Data held by Us about our
                Service users is among the assets transferred.
              </PRCompo1>
              <PRCompo1 subHeading="For other purposes:" childrenClass="mt-4">
                We may use Your information for other purposes, such as data
                analysis, identifying usage trends, determining the
                effectiveness of our promotional campaigns and to evaluate and
                improve our Service, products, services, marketing and your
                experience.
              </PRCompo1>
            </div>{" "}
            <br />
            <br />
            We may share Your personal information in the following situations:
          </PRCompo1>
          <ul className="mt-4 list-disc ps-4 sm:ps-8 md:ps-12">
            <li>
              <PRCompo1 subHeading="With Service Providers:">
                We may share Your personal information with Service Providers to
                monitor and analyze the use of our Service, to contact You.
              </PRCompo1>
            </li>
            <li>
              <PRCompo1 subHeading="For business transfers:">
                We may share or transfer Your personal information in connection
                with, or during negotiations of, any merger, sale of Company
                assets, financing, or acquisition of all or a portion of Our
                business to another company.
              </PRCompo1>
            </li>
            <li>
              <PRCompo1 subHeading="With Affiliates:">
                We may share Your information with Our affiliates, in which case
                we will require those affiliates to honor this Privacy Policy.
                Affiliates include Our parent company and any other
                subsidiaries, joint venture partners or other companies that We
                control or that are under common control with Us.
              </PRCompo1>
            </li>
            <li>
              <PRCompo1 subHeading="With business partners:">
                We may share Your information with Our business partners to
                offer You certain products, services or promotions.
              </PRCompo1>
            </li>
            <li>
              <PRCompo1 subHeading="With other users:" childrenClass="mt-4">
                when You share personal information or otherwise interact in the
                public areas with other users, such information may be viewed by
                all users and may be publicly distributed outside. Service.
              </PRCompo1>
            </li>
            <li>
              <PRCompo1 subHeading="With Your consent:" childrenClass="mt-4">
                We may disclose Your personal information for any other purpose
                with Your consent..
              </PRCompo1>
            </li>
          </ul>
        </div>
        <div className="PR_Page4">
          <PRCompo1
            subHeading="Retention of Your Personal Data"
            subHeadingClass="inline-block w-full"
          >
            The Company will retain Your Personal Data only for as long as is
            necessary for the purposes set out in this Privacy Policy. We will
            retain and use Your Personal Data to the extent necessary to comply
            with our legal obligations (for example, if we are required to
            retain your data to comply with applicable laws), resolve disputes,
            and enforce our legal agreements and policies.
          </PRCompo1>{" "}
          <br />
          <span>
            The Company will also retain Usage Data for internal analysis
            purposes. Usage Data is generally retained for a shorter period of
            time, except when this data is used to strengthen the security or to
            improve the functionality of Our Service, or We are legally
            obligated to retain this data for longer time periods.
          </span>
        </div>
        <div className="PR_Page5">
          <PRCompo1
            subHeading="Transfer of Your Personal Data"
            subHeadingClass="inline-block w-full"
          >
            Your information, including Personal Data, is processed at the
            Company&#39;s operating offices and in any other places where the
            parties involved in the processing are located. It means that this
            information may be transferred to — and maintained on — computers
            located outside of Your state, province, country or other
            governmental jurisdiction where the data protection laws may differ
            than those from Your jurisdiction.
          </PRCompo1>
          <PRCompo1>
            <br />
            Your consent to this Privacy Policy followed by Your submission of
            such information represents Your agreement to that transfer.
            <br /> <br />
            The Company will take all steps reasonably necessary to ensure that
            Your data is treated securely and in accordance with this Privacy
            Policy and no transfer of Your Personal Data will take place to an
            organization or a country unless there are adequate controls in
            place including the security of Your data and other personal
            information.
          </PRCompo1>
          <h1 className="mb-3  text-xl  font-semibold text-[#5DCBC4] sm:text-center sm:text-2xl md:text-3xl">
            Disclosure of Your Personal Data
          </h1>
          <PRCompo1
            subHeading="Business Transactions"
            subHeadingClass="inline-block w-full"
          >
            If the Company is involved in a merger, acquisition or asset sale,
            Your Personal Data may be transferred. We will provide notice before
            Your Personal Data is transferred and becomes subject to a different
            Privacy Policy.
          </PRCompo1>
          <PRCompo1
            subHeading="Law enforcement"
            subHeadingClass="inline-block w-full"
          >
            Under certain circumstances, the Company may be required to disclose
            Your Personal Data if required to do so by law or in response to
            valid requests by public authorities (e.g. a court or a government
            agency).
          </PRCompo1>
        </div>
        <div className="PR_Page6">
          <PRCompo1 subHeading="Other legal requirements">
            The Company may disclose Your Personal Data in the good faith belief
            that such action is necessary to: <br />
            <br />
            <ul className=" list-disc ps-4">
              <li>Comply with a legal obligation</li>
              <li>Protect and defend the rights or property of the Company</li>
              <li>
                Prevent or investigate possible wrongdoing in connection with
                the Service
              </li>
              <li>
                Protect the personal safety of Users of the Service or the
                public
              </li>
              <li>Protect against legal liability</li>
            </ul>
          </PRCompo1>
          <PRCompo1
            subHeading="Security of Your Personal Data  "
            subHeadingClass="inline-block w-full"
          >
            The security of Your Personal Data is important to Us, but remember
            that no method of transmission over the Internet, or method of
            electronic storage is 100% secure. While We strive to use
            commercially acceptable means to protect Your Personal Data, We
            cannot guarantee its absolute security. <br />
            <br />
            The Service Providers We use may have access to Your Personal Data.
            These third-party vendors collect, store, use, process and transfer
            information about Your activity on Our Service in accordance with
            their Privacy Policies.
          </PRCompo1>
          <PRCompo1
            subHeading="Usage, Performance and Miscellaneous"
            subHeadingClass="inline-block w-full"
          >
            We may use third-party Service Providers to provide better
            improvement of our Service. <br /> <br />
            <PRCompo1>
              <h1 className="font-semibold">Google Places</h1>
              Google Places is a service that returns information about places
              using HTTP requests. It is operated by Google <br />
              <br />
              Google Places service may collect information from You and from
              Your Device for security purposes. <br />
              <br />
              The information gathered by Google Places is held in accordance
              with the Privacy Policy of Google:
              https://www.google.com/intl/en/policies/privacy/
            </PRCompo1>
          </PRCompo1>
          <PRCompo1
            subHeading="Children&#39;s Privacy"
            subHeadingClass="inline-block w-full"
          >
            Our Service does not address anyone under the age of 13. We do not
            knowingly collect personally identifiable information from anyone
            under the age of 13. If You are a parent or guardian and You are
            aware that Your child has provided Us with Personal Data, please
            contact Us. If We become aware that We have collected Personal Data
            from anyone under the age of 13 without verification of parental
            consent, We take steps to remove that information from Our servers.{" "}
            <br />
            <br />
            If We need to rely on consent as a legal basis for processing Your
            information and Your country requires consent from a parent, We may
            require Your parent&#39;s consent before We collect and use that
            information.
          </PRCompo1>
        </div>
        <div className="PR_Page7">
          <PRCompo1
            subHeading="Links to Other Websites"
            subHeadingClass="inline-block w-full"
          >
            Our Service may contain links to other websites that are not
            operated by Us. If You click on a third party link, You will be
            directed to that third party&#39;s site. We strongly advise You to
            review the Privacy Policy of every site You visit. <br />
            <br />
            We have no control over and assume no responsibility for the
            content, privacy policies or practices of any third party sites or
            services.
          </PRCompo1>
          <PRCompo1
            subHeading="Changes to This Privacy Policy"
            subHeadingClass="inline-block w-full"
          >
            We may update Our Privacy Policy from time to time. We will notify
            You of any changes by posting the new Privacy Policy on this page.{" "}
            <br />
            <br />
            We will let You know via email and/or a prominent notice on Our
            Service, prior to the change becoming effective and update the
            &quot;Last updated&quot; date at the top of this Privacy Policy.{" "}
            <br />
            <br />
            You are advised to review this Privacy Policy periodically for any
            changes. Changes to this Privacy Policy are effective when they are
            posted on this page.
          </PRCompo1>
          <PRCompo1
            subHeading="Contact Us"
            subHeadingClass="inline-block w-full"
          >
            If you have any questions about this Privacy Policy, you can contact
            us: <br />
            <ul className="list-disc ps-4">
              <li>By email: example.com@gmail.com</li>
            </ul>
          </PRCompo1>
        </div>
      </main>
      <Footer />
    </section>
  );
}
